### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by premedios** [jamstack/jamstack.org#107]
Just another stupid "stack" created by kids who they know better than people who have been around since the start of the internet!

**Comment by DirtyF** [comment]
@premedios Funny to react this way, when it's just how a lot of websites works now. API request are still using HTTP, generated markup is still HTML, enhanced with modern JavaScript. It's the good ‘old stack taking advantages of today's APIs and automated workflows. As long as we don't receive any complaints from Sir Tim Berners-Lee, everything is fine 😄
