### ISSUE TITLE
Header UI is distorted

### ISSUE THREAD

**Issue by krishnatandon1208** [jamstack/jamstack.org#144]
While scrolling, the header seems to be distorted. 
Please see the image.
![jamstack_header_issue](https://user-images.githubusercontent.com/6280870/48017900-7c60f980-e155-11e8-8c21-ab3b08dbfb63.png)

**Comment by PEZ** [comment]
This PR fixes it: #144

**Comment by krishnatandon1208** [comment]
Hi,
Requesting you to verify it once. I am not able to replicate the fix i.e. the issue still persists.

**Comment by DirtyF** [comment]
@PEZ It should look like https://deploy-preview-127--jamstack-site.netlify.com/

**Comment by PEZ** [comment]
@DirtyF can you point out where it differs? I fail to see it

 It is late and I am tired, granted. :smile:

**Comment by krishnatandon1208** [comment]
Fxed 👍
