### ISSUE TITLE
JAMStack Lisbon meetup graphics 

### ISSUE THREAD

**Issue by PerrySetGo** [jamstack/jamstack.org#156]
Olá! Another day, another meetup. This time it's Lisbon!

Edit: here is the meetup link: https://www.meetup.com/JAMstack-Lisbon/

We need the standard assets for Lisbon - here are the landmarks Nuno has suggested for the graphics. He says:

In terms of landmarks check the Torre de belem, 
https://en.wikipedia.org/wiki/Belém_Tower

the bridge
https://en.wikipedia.org/wiki/25_de_Abril_Bridge

and the main square
https://en.wikipedia.org/wiki/Praça_do_Comércio#/media/File:Lisbon_main_square_(36622604910).jpg

He is organizing a meetup in january so we have a little bit of time for this. 

Muito obrigado!

**Comment by PerrySetGo** [comment]
do we have an update on when this might be ready? thanks!

**Comment by rafaelconde** [comment]
Boom 💥 

PR 👉 https://github.com/jamstack/jamstack.org/pull/162
Assets 👉 [JAMstack_Lisbon Assets.zip](https://github.com/jamstack/jamstack.org/files/2727928/JAMstack_Lisbon.Assets.zip)

**Comment by philhawksworth** [comment]
Wonderful! Thanks @rafaelconde.
PR merged. Assets forwarded.
