### ISSUE TITLE
Code of Conduct for events

### ISSUE THREAD

**Issue by deammer** [jamstack/jamstack.org#187]
Hi folks! I'm one of the organizers of the Seattle JAMstack event and I've been looking for a decent code of conducts for our events. I thought it'd be great to host it on this site so that other events could easily link to it.

I opened #186 for this purpose. Feedback is welcome! Cc @PerrySetGo @biilmann

**Comment by PerrySetGo** [comment]
@deammer  this is a great initiative. We definitely want to start encouraging all meetups to have a Code Of Conduct to make sure meetups feel safe to everyone & there is a clear process of accountability if something goes wrong. I'm actually in a CoC training tomorrow so am actively working on this. More very soon, thanks for getting the ball rolling.

**Comment by deammer** [comment]
@PerrySetGo that's fantastic! Let me know if/how I can help.

**Comment by PerrySetGo** [comment]
just commenting here to say this hasn't gotten forgotten about. we will begin addressing this this quarter. 👍

**Comment by PerrySetGo** [comment]
I am editing the CoC today :)

**Comment by deammer** [comment]
@PerrySetGo took care of this in #204 🎉

**Comment by PerrySetGo** [comment]
thanks for helping me be accountable!  :)
