### ISSUE TITLE
How about Functional + API + Markup

### ISSUE THREAD

**Issue by MatheusRV** [jamstack/jamstack.org#189]
JavaScript is a trend, we all know. But we must not forget that it is possible to use functional language to implement practically the same functions that JavaScript performs for headlessCMS and SSG's. So the name given to architecture is not wrong? I'm a scientist and I'm dedicating my monograph to explaining how this new platform works.

**Comment by DirtyF** [comment]
FAME would be a nice acronym indeed 😄

**Comment by MatheusRV** [comment]
Famestack :)

**Comment by MatheusRV** [comment]
But i'm considering in call this as Hyper Static Stack.

**Comment by PerrySetGo** [comment]
hi, interesting take. I definitely encourage you to discuss this in Community community.netlify.com but if there isn't a specific request here i will close this issue :).

**Comment by MatheusRV** [comment]
https://community.netlify.com/t/how-about-functional-api-markup/403
