### ISSUE TITLE
Nav looks broken

### ISSUE THREAD

**Issue by lesliecdubs** [jamstack/jamstack.org#214]
Hi team! The nav on secondary pages of the site appears broken:

![](https://user-images.githubusercontent.com/3902488/58361757-7531dc80-7e56-11e9-9142-3a1101adf076.png)

**Comment by connorholyday** [comment]
I reckon it might be a case of an ad-blocker hiding the `.promo-banner`
![image](https://user-images.githubusercontent.com/4559119/61863333-4cb27700-aec7-11e9-8abf-f020d86bd7c0.png)

I reckon we could fix this by wrapping the banner and the adjacent `<header />` in a wrapper component that handles the fixed positioning. That way we can remove the top-margin from the header and the empty space will collapse if the promo-banner is hidden/removed.

Thoughts? Happy to put a PR together in a bit

**Comment by jbarth-et** [comment]
It looks like the banner has been removed now, but not the spacing, so it looks like the first screenshot again (just randomly passing by)

**Comment by lesliecdubs** [comment]
Thanks @jbarth-et, there's a new banner up so I'm going to close this issue since the bug is no longer occurring.
