### ISSUE TITLE
Story breeding example in loads crypto jacking lib. 

### ISSUE THREAD

**Issue by JoshMilo** [jamstack/jamstack.org#220]
In the examples page, the Story breeding example uses crytpo mining.

<img width="1317" alt="Screen Shot 2019-06-02 at 10 03 29 AM" src="https://user-images.githubusercontent.com/1663425/58764603-f4da3e00-851d-11e9-9227-f171187cf5e7.png">

**Comment by plasmadice** [comment]
I can confirm this. Please remove the site from examples. The script is blocked at my work, but others may not be so lucky.

**Comment by philhawksworth** [comment]
Many thanks @JoshMilo, @plasmadice!
Site removed.
