### ISSUE TITLE
Guide to build a Jamstack site using Hugo and ButterCMS api

### ISSUE THREAD

**Issue by pineapple-content** [jamstack/jamstack.org#227]
This blog post in an in-depth Jamstack guide for beginners - it covers the foundations, history and understanding of the Jamstack architecture. It also provides a step-by-step tutorial on how to build a website with Jamstack using Hugo for Markup and ButterCMS API. 
https://buttercms.com/blog/what-is-jamstack

**Comment by jakelumetta** [comment]
Hi @huguestennier  - just wanted to follow up on this. Is opening an issue the best process for suggestions?

**Comment by philhawksworth** [comment]
This has been added to the resources page now. And also to the list of resources in the upcoming v2 of the site. Thanks for contributing it!

**Comment by jakelumetta** [comment]
Thanks @philhawksworth !
