### ISSUE TITLE
Error with node 11+

### ISSUE THREAD

**Issue by oktalk** [jamstack/jamstack.org#246]
Attempting to `yarn start` with `node 12` and I ran into errors. I dropped down to `node 10.0.0` and it worked. Just an FYI.

```
jamstack.org git:(master) ✗ yarn start              
yarn run v1.17.3
$ gulp server
[16:00:25] Failed to load external module @babel/register
[16:00:25] Requiring external module babel-register
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
```

**Comment by zachleat** [comment]
Hey, just going through old issues and I wasn’t able to find any reference to `primordials` in the code base. We don’t use babel any more either so I believe this is fixed.
