### ISSUE TITLE
Sitemap errors

### ISSUE THREAD

**Issue by scottmathson** [jamstack/jamstack.org#260]
https://jamstack.org/sitemap.xml referencing `DEPLOY_PRIME_URL` as base url for the site and subdirectory pages, causing invalid `<loc>` throughout the sitemap file.

Sitemap isn't formatted correctly for submission to tools like Google Search Console and crawl-ability then broken for bots trying to follow these referenced paths.

---

Generated sitemap file markup:

![current jamstack.org/sitemap.xml](https://user-images.githubusercontent.com/25587929/70160410-a9911b80-1677-11ea-93c7-bc6616201025.png)

**Comment by zachleat** [comment]
I think we can close this now—seems fixed.
