### ISSUE TITLE
Discussion: Tech choices for jamstack.org v2

### ISSUE THREAD

**Issue by philhawksworth** [jamstack/jamstack.org#277]
# Discussion: Tech choices for jamstack.org v2

## Goals of this issue

- Share the current suggested tooling for the next iteration of jamstack.org
- Invite comments from the community to help steer some of the decisions
- Together, identify an approach which best serves the functional needs of the site, and also presents the most efficient and accessible approach to including content and implementation contributions from the community

## High level requirements

- Generation of a site using suitable static site generator or similar build automation
- A development pipeline which can be simply and confidently replicated by contributing developers
- A resultant site which embodies sound JAMstack principles:
  - Complete, viable views generated at build-time
  - No dependency on client-side JavaScript for core content
  - A Progressive Enhancement approach to any additional feature requiring client-side JavaScript
  - A site deployable entirely to a CDN (provided for the project by [Netlify](https://netlify.com))
- A low barrier to participation in terms of technical expertise

### SSG: [Eleventy](https://11ty.dev)

Eleventy has the following properties which I think make it a good candidate for this project:

- **Simple to bootstrap**. Since it is entirely JavaScript and easily provisioned via an `npm install` developers do not have to leave the comfort of node and local JavaScript to configure their environments.
- **Framework-free**. Eleventy does not yield or require a JavaScript framework as part of its output. This mean that there are fewer concepts to understand and maintain than with other, more functionally powerful, but complex options.
- **Explicit and straightforward**. Eleventy only outputs what is explicitly defined meaning that it can be more approachable and maintainable for a broader group of developers.
- **Templating options**. Support for many templating syntaxes makes it more likely that we can select one that has good community appeal.
- **Compilation speed**. Although this site is not likely to have thousands of pages, compilation speed can still impact developer experience and deployment optimisations. Eleventy has speedy build times.

### Templating: [Nunjucks](https://mozilla.github.io/nunjucks/) or [Liquid](https://shopify.github.io/liquid/)

Both of these options are:

- Popular and well documented.
- Expressive enough to support the site features we might want. But not too complex.
- Have useful template inheritance.
- Extensible through Eleventy.
- Relatively simple to read and comprehend.

My personal preference is for Nunjucks, just because I really like its syntax. But more people might be familiar with Liquid which could make it a more obvious choice.

### CSS: [TailwindCSS](https://tailwindcss.com/)

Potential hot-drama in this recommendation!

Approaches to structuring and maintaining CSS vary differently. And maintaining CSS over a long period of time and with a disparate group of contributors can quickly become difficult. With TailwindCSS we have the ability to build on utility classes which transcend not only projects, but also entire development teams. I submit that using this will bring:

- Fewer reasons for people to need to write any CSS at all as part of their code contributions
- A basis for good structural conventions by default
- A simple build pipeline yielding optimized, purged CSS
- A more intuitive development experience when adding visual components _for those familiar with TailwindCSS_

Possible resistance to using Tailwind might be:

- It adds lots of css classes into your markup. (this can be mitigated, but still..!)
- Not everyone knows it, but people know CSS
- and probably more

## Onwards

...I'm keen to discuss these things and get opinions here in this issue. I feel it would be a good choice, but anticipate some debate.

Any strong feelings or suggestions to voice? Your contribution to the discussion is much valued.

**Comment by colbyfayock** [comment]
thanks for sharing this

it would be interesting to build this out in both a starter-like and theme fashion, where community organizers can quickly spin up a site that would immediately conform to the branding. if built into a packaged theme, that would be nice to be able to easily update the package to pull in the new styles, rather than having to make any tweaks manually

only concern with a CSS library would be if it's considered overkill depending on the depth of the site and how much customization would be needed to lay on top of it to make up the site given there's a lot of nice ways to get far with native CSS these days, but it would still be a good argument for supplementing people's ability to easily spin up an associated site with an already documented way to get productive

**Comment by philhawksworth** [comment]
Thanks @colbyfayock.

That's an interesting thought about the site code having some reusability beyond this site, and perhaps being able to offer a good starting point for community organisers sites _if_ they choose to use it.

I'm a little cautious about scope creep, and if making the site cater for many things might slow down progress... but it's good to capture this as a consideration and potential capability to factor in.

In a separate issue, I'll soon share the Information architecture and some other high-level content planning for the site. I'm hoping to invite feedback in a similar way on that. Your suggestion should certainly be added to the suggest requirements, even as a stretch goal.

I'll include it when I create the issue.

Regarding the need to add a CSS library - oh yes, I have no doubt that we can do everything we need to realise the design without a CSS library. I'm thinking more about the ability to not write too much in terms of custom CSS for the site vs using pre-existing utility classes and therefor needing people to write little or no CSS at all throughout the maintenance and evolution.

Thanks for these thoughts.

**Comment by jameesy** [comment]
I think these choices are very sensible and well thought out. 

I think Tailwind is actually a really good shout in this instance. I think its a decent enough trade off for people having to familiarise themselves with the syntax for the benefits of structure over time.

**Comment by philhawksworth** [comment]
Thanks @jameesy! That's my thinking. 
Let's see how strong the feelings are either way before settling on a decision.

**Comment by graygilmore** [comment]
> Potential hot-drama in this recommendation!

Writing CSS is one of my favourite things to do but I think Tailwind makes a lot of sense for a project like this (as much as that pains me to admit 😝).

> Eleventy [...] Framework-free

This feels right in the sense of trying to stay as neutral as possible but I wonder if it's to the detriment of somebody learning? A lot of Bootcamp grads, for example, come out knowing a particular framework and I think we can be honest with ourselves that it's most likely React at this point. I think it's easier for experienced developers to see how one framework can translate to another but it could be more difficult for beginners. I *think* being neutral is probably the right choice but it would be interesting to hear from others!

**Comment by jameesy** [comment]
Is there anything you require help with at this stage @philhawksworth outside of technical discussions?

**Comment by philhawksworth** [comment]
Thanks @graygilmore! This is helpful.

While I'm all for the code for this site being a useful reference, that isn't its primary purpose, so we should keep our primary objectives our front. However your comment that many people arriving here might be most comfortable contributing using React is well worth talking over a little.

One of the requirements I listed (and am happy to debate) is:

> No dependency on client-side JavaScript for core content

My logic here is:
- A site like this should not need to depend on JavaScript to render dynamically in the user's device
- Serving the content in HTML is advantageous for:
  - Accessibility
  - SEO
  - Performance (particularly for a global community where JavaScript performance on devices can be a bottleneck)

No doubt, React is valuable piece of the JAMstack landscape, but I'd argue that it is not necessary for a content site such as this, and adds some complexity which we might be best avoiding. We'd not be switching it for a different, less common JS framework. They'd be no JS framework. 🥳

The code for the site _would_ include concepts and conventions that I think should be familiar and/or useful to a wide range of web developers though. Such as:

- Scripted builds via npm
- JavaScript for configuration and utilities at build time
- HTML partials for simple reusable components
- Structured data files for content contributions
- Local development utilities

Eager to hear more thoughts around this.

**Comment by colbyfayock** [comment]
💯 for the idea of no client side dependency for this project. i ❤️ react but i think it would also serve as a great use case example to show people you can get by without it with good benefits

**Comment by philhawksworth** [comment]
Thanks @jameesy! Soon!

I'll share some more things to discuss and contribute to  over the coming days. In particular, I'd like to gather thoughts on the content and URL structures. I've been working on a starting proposal for that, but it deserves its own issue to track the discussion. I'll post that soon!

**Comment by graygilmore** [comment]
> Serving the content in HTML is advantageous

👍 Completely agree with this! I agree that no matter what tooling is used the site should serve up HTML files for content. 

I was thinking more along the lines of templating. Instead of Eleventy and Liquid, for example, we could be using Gatsby. Still building out HTML files with content in them but doing it in a more opinionated way. I'm *mostly* playing devil's advocate here because I think it's worth discussing at the offset but I think at the end of the day I also favour the no-framework approach.

I would expect a no-framework approach to still be fairly accessible to new contributors due to the more simplistic nature *and* would make sure that it's not alienating to those that don't know React.

**Comment by philhawksworth** [comment]
> I'm mostly playing devil's advocate here because I think it's worth discussing at the offset

Yay @graygilmore! 💯

There is a lot to be said for the popularity of Gatsby, and the component-based development model it leads you towards. I've not personally seen it used to output a site which is all HTML with no bundled client-side app to do onwards hydration. I'd be keen to learn about that regardless of the direction here!

And yeah, I'm with you on the approachability of a no-framework solution. I'd hope that it would be equally grokable by people who specialise in React, Vue, Angular, JavaScript, or just plain old semantic HTML.

**Comment by philhawksworth** [comment]
Thanks for the input into this. It looks like people are comfortable with the proposed approach. Development is now underway with these tools. Work in progress can be found on the `next` branch of this repository.
