### ISSUE TITLE
Discussion: evolving the JAMstack branding design

### ISSUE THREAD

**Issue by philhawksworth** [jamstack/jamstack.org#292]
When the team at Netlify first created the branding for the jamstack.org site, its needs were rather different. In the time since then, jamstack has grown to include:

- Dozens of community meetup groups
- JAMstack Conferences
- Adoption into the parlance of many services and organisations
- References in technical writing
- A community slack

...and much more.
As the category scales, so too should the identity. 

## This issue exists to:

- Share the criteria and requirements for an updated logo and branding for JAMstack.
- Share some of the design iterations and thinking
- Invite feedback
- Show the current work in progress

## Logo mark requirements and considerations

1. Logo artwork needs to be versatile, and hold up at a variety of sizes and applications (digital, print, embroidery, screen printing, etc)
2. Logo color considerations:
    - Logo needs to work in flat color (no gradients or halftones)
    - Logo needs to have both a two-color version with a one-color alternate.
    - Logo should also support knockout applications (white logo on dark backgrounds)
3. Logo needs to have both a jewel (think) and the wordmark (think the world "Apple").
4. Logo needs to be designed to allow for three variations when considering the jewel of the logo and the wordmark of the logo:
    - Jewel to the left, wordmark to the right (horizontal version)
    - Jewel centered above the wordmark (vertical version)
    - Jewel alone, independent of the wordmark (simple "favicon" version)
5. Jewel of the logo should allude in some manner to a stack of three components
6. Logo needs to be vector shapes only, to support SVG format for web / digital and EPS format for print applications. 
7. Logo should feel modern, as JAMstack is a modern approach to building web applications
8. Logo should feel at home alongside jamstack ecosystem logos as well as logos for enterprise services like AWS.
9. Logo shape should not be confusingly similar to other logos in the general ecosystem
10. Logo colors should be fairly unique in the space. (In our ecosystem research, blues, greens, purples, and reds seemed to be the most widely used among ecosystem partners.)

**Comment by philhawksworth** [comment]
Sharing some work in progress - typography exploration for the wordmark

![exploration-typography](https://user-images.githubusercontent.com/5865/77187370-41523280-6acc-11ea-984b-1516b20d6348.png)

There has been some interesting discussions contributing to this work in progress. One thought relating to the emphasis of JAM and the discussion about how much emphasis to give to the original acronym (#279) - a word mark which is _entirely_ lowercase is less likely to influence/confuse the issue than using either `Jamstack` or `JAMstack`. The same logic might apply to an all caps wordmark.

**Comment by philhawksworth** [comment]
Sharing some work in progress - colour exploration for the jewel

![exploration-colors](https://user-images.githubusercontent.com/5865/77187847-01d81600-6acd-11ea-9291-f3ac808f2ccd.png)

Whatever colour emerges as the primary theme/accent colour, the wordmark and jewel will need to be able to function on lights and dark backgrounds, and when used in many sites where it might appear on other coloured backgrounds. A strong silhouette is important for that.

**Comment by colbyfayock** [comment]
throwing out another idea i put together. it doesnt have a specific jewel as that one does, but in case it sparks any ideas. would need to probably be tightened up a bit

![image](https://user-images.githubusercontent.com/1045274/77189744-6f287e80-6aae-11ea-9d3f-267490a1a1f4.png)

if it's liked, the jewel could be a shortened version using just the JAM, though would probably need to be adjusted to look better on its own

**Comment by philhawksworth** [comment]
So cool that you made holo stickers of that, @colbyfayock!
We might want to be a little cautious about echoes of Amp.

<img width="337" alt="Screenshot 2020-03-20 at 19 19 03" src="https://user-images.githubusercontent.com/5865/77198930-d4e12e80-6adf-11ea-8a12-216edb0e6302.png">

**Comment by philhawksworth** [comment]
Here are Some more explorations about how a logomark might work on backgrounds of different colours and textures, so that it can be used within the context of other brands and sites. 

And also some experiments for how meetup groups could get autogenerated assets for their cities.

![meetup-punchout](https://user-images.githubusercontent.com/5865/77199164-4f11b300-6ae0-11ea-812c-5f44c05f4b0c.jpg)

**Comment by jameesy** [comment]
This is looking so good @philhawksworth

**Comment by MatheusRV** [comment]
JAMstack is definily not a good name, how about functional + api + markup?

**Comment by philhawksworth** [comment]
I'm afraid that changing this name is not in the scope of this discussion, or something that we are considering, @MatheusRV.

**Comment by philhawksworth** [comment]
We should consider how the discussion about reaching a consistent way to write "Jamstack" might factor in on this design too. #279

**Comment by brooksztb** [comment]
I am by no means a graphic designer but this is a mockup I made of something I thought would be a fun concept for JAMStack. 

![JAMStack Logo Mockup](https://user-images.githubusercontent.com/31398142/78385156-aad84380-7598-11ea-915d-4f1cd3905cab.png)

I've seen the jar of jam being used a bit for talks and meetups and I also think it makes it a little unique. It also could have the jar cut into the 3 parts of the stack with say a center bit that the jar picture that I used kind of has. I thought it went along the lines of something like how React has the atom as their logo. I also think a jar of jam fits well for a jewel of the logo.

**Comment by philhawksworth** [comment]
Thanks @brooksztb!

I've seen a number of literal "jam" visualisations. Netlify have been down that road too for various events and short run stickers. They can be fun!

I wonder how distinctive this would be when used in different colourways and as a monochromatic version for punch-outs over different colors and textures. 

Regardless of how much this may or may not be suitable for professional and enterprise settings too, I'd personally be quite taken with some similar things out in the world. Even if informal nods to Jamstack if not the official logo.

**Comment by bigash42** [comment]
Sharing the next round of logo iterations based on recent feedback. Changes include: 

- Updated wordmark to reflect the decision in #279 .... You'll see the new logo version reflects a capitalized Jamstack which will help drive consistency in the naming convention. 
- Fixed spacing between icon and wordmark 
- Adjusted sizing of icon in ratio to wordmark 
- More color explorations to show flexibility of design
<br>

![Jamstack Logo April](https://user-images.githubusercontent.com/14846680/79023271-b5fd1780-7b34-11ea-9d20-a4ae5ac394e6.png)

<br>

We're almost there with the logo thanks for all the useful feedback so far!

**Comment by TSFoster** [comment]
Hi, I just stumbled across this while browsing the issues page, so I hope I'm not barging in among regular contributors.

I like the new branding! I wondered if you had considered making the spacing between the segments that make up the 'J' in the icon a little larger? The two lines that are formed between the gaps seem a little small compared to the rest of the forms in the icon, and I think they get a bit lost, particularly in smaller sizes.

![jamstack](https://user-images.githubusercontent.com/510520/79334865-f71c6f80-7f18-11ea-9b60-af6f3e080829.png)

**Comment by bigash42** [comment]
Hey @TSFoster - always welcome and thanks for chiming in. This is a really great point and mockup. 

We did explore the line weight in some early rounds and I thought we ended up somewhere closer to the 7px. Working on a new round right now to fix. Thank you!

**Comment by philhawksworth** [comment]
Closing this discussion now that the new jamstack.org has launched.
Specific issues, suggestions, and discussions are of course welcome.

**Comment by iaeiou** [comment]
Nice!
What is the license of this logo?
