### ISSUE TITLE
404 for examples page

### ISSUE THREAD

**Issue by Chr1d5ter** [jamstack/jamstack.org#30]
On browsing the site https://jamstack.org/examples it retuns with a 404

Cheers

**Comment by DirtyF** [comment]
https://jamstack.org/examples/ looks fine from here.

**Comment by Chr1d5ter** [comment]
There's a 301 redirect issue. The top navigation doesn't have the trailing slash. Click on examples in the top menu :)

**Comment by DirtyF** [comment]
I'm not experiencing any issue with the redirection.

```
❯ http https://jamstack.org/examples
HTTP/1.1 301 Moved Permanently
Age: 7190
Cache-Control: public, max-age=0, must-revalidate
Connection: keep-alive
Content-Length: 26
Content-Type: text/plain
Date: Tue, 21 Mar 2017 11:58:46 GMT
Etag: "a3de1e20bd28da881df2a3e24b4fbd1e-ssl-df"
Location: /examples/
Server: Netlify
Strict-Transport-Security: max-age=31536000

Redirecting to /examples/
```

**Comment by Chr1d5ter** [comment]
I'm in the UK. I've tried on my mobile and still see the 404. I just tried on pingdom tools and it works.

It deffo 404s for me just on the examples page

**Comment by calavera** [comment]
Thanks for reporting this. It looks like Google's DNS had an issue last night that affected part of our infrastructure, that might have caused this issue. The page is being served correctly now, so I'm going to close it, but feel free to reopen if you bump into the same problem again.
