### ISSUE TITLE
Okay, "what is the Jamstack?" and "why the Jamstack?", but *who* is the Jamstack?

### ISSUE THREAD

**Issue by JamesCropcho** [jamstack/jamstack.org#307]
Hello:

I hope this message finds you well.

I am unable to find on the pages at jamstack.org any information about the organization.

1) Who founded Jamstack and in which country and year?
2) Beyond advancing adoption of this new development paradigm ("The Jamstack"), what is the organization's mission?
3) Where does the organization receive its funding?

Pardon me if this this issue tracker is not the correct place to ask a FAQ-style question; I did not see any other means of contact.

—James

**Comment by jaredcwhite** [comment]
Well it's not an organization per se. The term itself was coined by Mathias Biilmann of Netlify and they've generally helped spearhead the marketing of the idea. But basically Jamstack tech is built by and for the broader web development community at large.

**Comment by zachleat** [comment]
It’s probably best to start at the beginning with Matt Biilmann’s original Jamstack talk at Smashing Conf 2016. This is linked up from the home page of jamstack.org: https://jamstack.org/#:~:text=Rise%20of%20the%20Jamstack

I’d also check out the Jamstack resources on Jamstack TV too: https://jamstack.org/tv/
