### ISSUE TITLE
Slack link on Jamstack.org is expired

### ISSUE THREAD

**Issue by safoo** [jamstack/jamstack.org#333]
When clicking the link on the footer at jamstack.org to join the slack, the link is expired.

![image](https://user-images.githubusercontent.com/1414129/86694749-c18b9d80-bfc0-11ea-9051-a7eaf9206f41.png)

Expected behavior: the link should be active so folks who want to join the slack can sign up.

**Comment by safoo** [comment]
@philhawksworth is this something you can help with our route to someone who can?

**Comment by philhawksworth** [comment]
Looks like these links which "do not expire" do expire after a certain number of people use them. 🧐

I've refreshed the invite link (which lives behind a redirect, so we can always use share the same link to invite people: https://jamstack.org/slack)
