### ISSUE TITLE
Re-add filters and sorting by programming lanuage on Site Generators and Headless CMS pages

### ISSUE THREAD

**Issue by kolebayev** [jamstack/jamstack.org#401]
Hi, it will be useful to sort [generator cards](https://jamstack.org/generators/) by programming language.
Example attached below, text names can be replaced with logos
![generators-sorting-update](https://user-images.githubusercontent.com/24884175/95435262-083fb980-095b-11eb-89c6-fbf439bba7f7.png)

**Comment by philhawksworth** [comment]
Thanks @kolebayev! 
Yes, we plan to get filtering in soon. That's a good enhancement.

I like the idea of showing some of the branding for the generators too, although only a fraction of the long list have logos. We'll have to give that some thought on how it might best be flexible.

**Comment by ajmas** [comment]
- For the logos, maybe keep the name, but add an avatar style logo (square zone) to the left, with a a fall back logo.
- For filtering, I imagine this would be via frontend JS? Would you want to go JS+JQuery, pure JS or take some other approach?

**Comment by ajmas** [comment]
Is the site purely static? If it is, then it sound like generating a keywords JSON that could be loaded and searched could be an approach.

**Comment by noraj** [comment]
Why introducing regressions from staicgen.com?

**Comment by ajmas** [comment]
@noraj you mean staticgen.com (which redirects to jamstack.org)? Are you meaning to take reintroduce old code, or something else?

**Comment by noraj** [comment]
> @noraj you mean staticgen.com (which redirects to jamstack.org)? Are you meaning to take reintroduce old code, or something else?

On staticgen.com there were filtering and sorting and on the new jamstack.org there isn't anymore so that's a regression of features, the new website may look more modern but is less clear and with less features.

**Comment by Buzut** [comment]
If you add filters, in addition to language, you can also add by templating engine and licence (as this was the case on staticgen.com).

[![staticgen.png](https://i.postimg.cc/vT9WWG2Z/staticgen.png)](https://postimg.cc/XBjGW60R)

And the same goes for CMS being able to filter by CMS type (API vs git-based), SSG compatibility and licence (and or ability to self host) is of paramount importance. It saves yourself a lot of time if what you need is Git based compatible with 11ty (you'll have less than 5) vs having to read everything if there's no filtering available.

[![headlesscms.png](https://i.postimg.cc/QNRmVyYM/headlesscms.png)](https://postimg.cc/K4DBHJ2X)

**Comment by zachleat** [comment]
## Staticgen

* via https://5f7b8cfe86cd4200078f6071--staticgen.netlify.app/

Previous sort functionality:

![image](https://user-images.githubusercontent.com/39355/100652249-3d89d780-330c-11eb-8b70-3a663b675f38.png)

## Headless CMS

*  via https://5f7b786d676f5539dcd3cfc1--headlesscms.netlify.app/

Previous sort:
![image](https://user-images.githubusercontent.com/39355/100652359-71fd9380-330c-11eb-9b2f-1569571741cf.png)

CMS type: 
![image](https://user-images.githubusercontent.com/39355/100652415-83df3680-330c-11eb-9ca0-9692ea49ac93.png)

License:
![image](https://user-images.githubusercontent.com/39355/100652431-8a6dae00-330c-11eb-839c-ffff67246c50.png)

**Comment by zachleat** [comment]
Filed #473 as a separate task if you’d like to follow along there.

**Comment by zachleat** [comment]
These changes are pushed up and y’all can have a sneak peek if you’d like! https://github.com/jamstack/jamstack.org/pull/472

**Comment by zachleat** [comment]
🚢🛳⛴🚀📦 (shipped)

**Comment by zachleat** [comment]
Filed the logos idea at #477.
