### ISSUE TITLE
Adding feature keywords or feature matrix

### ISSUE THREAD

**Issue by ajmas** [jamstack/jamstack.org#410]
Given then strength, weaknesses and focuses of the different CMSs, it would be useful to know what features are supported by each site-generator and headless CMS.

As an example, to have an indicator as to whether multi-lingual support is provided by each and in what form. 

Thinking this would be via keywords added to the front-matter. The keywords could be free-form or limited to a set of recognised keywords, such that if an unsupported keyword is provided, then it would not be displayed on the page. 

Going further, the keywords could be broken down into "strongly supported" and "supported", to have an indication as to how well that functionality is provided for.

Would this be of interest and in what form does the team think it should take?

**Comment by vwkd** [comment]
This was possible before on [staticgen](https://www.staticgen.com/] and [headlesscms](https://headlesscms.org/) before they moved everything over to here. I liked the filters as well as they made things much easier, e.g. find all static site generators written in JavaScript that use EJS templates.

I wonder if they removed that on choice or just didn't get around to implement it again.

**Comment by zachleat** [comment]
@vwkd The latter—it will return!

**Comment by zachleat** [comment]
I think we should probably regroup around this functionality at #401 and treat this as a duplicate. If there are additional nuances not represented over there, please feel free to add additional comments at #401—thanks!
