### ISSUE TITLE
Jamstack Community - Adding location filters/tags to find local groups

### ISSUE THREAD

**Issue by bigash42** [jamstack/jamstack.org#476]
As we grow the global community with new groups, it's getting difficult to "find a local group near you" but searching a long alphabetical list by city name. It would be great if we can add some filtering or tags by `continent` and `country` 

https://jamstack.org/community/

**Comment by zachleat** [comment]
Probably a light lift here as we could re-use `<filter-container>` from #401

**Comment by tabar** [comment]
Added to the sprint

**Comment by zachleat** [comment]
PR is up! https://github.com/jamstack/jamstack.org/pull/512

**Comment by zachleat** [comment]
🚢🛳⛴🚀📦-ed!
