### ISSUE TITLE
Starting a meetup group in Brasília, Brazil.

### ISSUE THREAD

**Issue by fsegall** [jamstack/jamstack.org#487]
## Hi, I'm Felipe from **Brasília, Brazil**. 

I want to get in touch with people that are into building apps with the JavaScript ecosystem following the **JAMstack** approach. I'm interested in learning by doing. I've just started a blog [here](`https://fsegall.com`) where I write about the stages of building an app from idea to _**MVP**_ (minimum viable product). If this resonates with you, let's schedule an online meeting (for now) at the beginning of January at meetup.com. We can even do this monthly to develop projects.

### Contact: segall.felipe@gmail.com.

Take care!

## Olá, sou o Felipe aqui de **Brasília**. 
Quero entrar em contato com pessoas interessadas em criar apps com o ecossistema JavaScript seguindo a abordagem do **JAMstack**. Estou interessado em aprender fazendo. Eu criei um blog recentemente [aqui](`https://fsegall.com`), onde eu escrevo sobre as fases de se construir um app partindo da ideia até um  _**MVP**_(produto mínimo viável). Se isso também te agrada, bora marcar uma conversa online no começo de Janeiro no meetup.com. Podemos até fazer reuniões mensais para desenvolver projetos.

### Contato: segall.felipe@gmail.com.

Até!
---

# ✨ But before you do, there are a few things to know✨

Please take a look at this information before submitting your issue.

## Before starting a new community group

1. **[Check if there is already an official community](https://jamstack.org/community) in or near your city** - If so, it would be worth joining and supporting that group before deciding to add another. And the organizers of Jamstack groups are likely to welcome some support.
1. **Organizing an official group takes some commitment** - We're so excited that you've come this far, and we want you to succeed. We ask orgaizers to aim to hold meetings (physical or virtual) at least 3 times a year.

## What you need

1. **An online event space** - Most groups use Meetup.com or Facebook to coordinate their events, but you can use a different tool of your preference. What we encourage is that organizers publish events publicly on a neutral platform.
1. **A published and actionable code of conduct** - To help the community stay inclusive, safe, and welcoming. 

### Resource kit

We'll provide a resource kit with logos and branded assets for you to use. We'd like you to make use of the official Jamstack logo where approporiate, but don't let us stiffle your creativity. Some meetups have also added their own fun aesthetic and that's great too.

### Links and listings

We'll add a link to your events page to the [community section](https://jamstack.org/community) of the official Jamstack site. And if you provide a feed of your upcoming and previous events, we'll also add your events to the listings.

### Community and support

Each Jamstack community group gets their own channel in the [Jamslack](https://jamstack.org/jamslack) to help coordindate your event and communicate with your local community.

You can also speak to other group organizers and reach us for support via in the Jamslack as members of the private organizers admin channel.

### Code of Conduct

We have [a boilerplate code of conduct]() which you can use as a starting point. Please note that you will need to customise this for you and your group. It is vital that the information about how people can contact you and how action may be taken is correct for your group rather than being generic.

### Content and speakers

Recruiting speakers and putting together compelling content can be one of the biggest challenges for User Group leaders. We encourage you to reach out to your fellow user group leaders via [Slack](https://jamstack.org/slack) for ideas, and even consider partnering with them for virtual events or workshops.

## Jamstack Conf

[Jamstack Conf](https://jamstackconf.com) is an annual event for the global Jamstack community and provides a great opportunity for local community groups to participate, apply for awards, and share their knowledge. Active Jamstack user group leaders receive special incentives and activities during this event, and we're keen to get them more involved in helping shape the event. You can [watch videos](https://www.youtube.com/playlist?list=PL58Wk5g77lF94tg-F3y5zRyDeLVhTDnTg) from recent events to help spur content ideas and identify potential speakers for your meetup

**Comment by bigash42** [comment]
Hi @fsegall! Thanks for taking the first step in starting a local Jamstack group in Brazília! Please fill out the following information and next steps! 

**The city or region for you new Jamstack Community: 
When you plan to hold your first event: 
How regularly you plan to meet: 
How else we might be able to help:** 

You'll also need to create a public group where people can find information about your events. We'll need this to link from your group on jamstack.org/community. We suggest meetup or facebook, but it's up to you were you host, just as long as it's open and discoverable. ✨ Remember to have a code of conduct on your group page.

**Comment by fsegall** [comment]
*Hi Ashlyn,*




*The city or region for your new Jamstack Community: Brasília, Brazil -
DFWhen you plan to hold your first event: 01/16/2021How regularly you plan
to meet: MonthlyHow else we might be able to help: For now just me, but
I'll add someone soon.*
*I'll make the arrangements for the meetup link.*
*Thanks a lot! Happy new year!*

**Comment by domitriusclark** [comment]
Hey! I see you filled a bunch of information already (but from a while ago) 

I've recently taken over handling support for communities and meetups. 

This something you're still interested in?
