### ISSUE TITLE
Starting a meetup group in Amsterdam, The Netherlands

### ISSUE THREAD

**Issue by Dawntraoz** [jamstack/jamstack.org#488]
You're interested in starting a Jamstack community in your area?
AMAZING! We're keen to help. 🥳

## Please tell us:

1. **The city or region for you new Jamstack Community**: Amsterdam, The Netherlands
1. **When you plan to hold your first event**: April 1st
1. **How regulalry you plan to meet**: Every four month
1. **How else we might be able to help**: Being in contact with PassionatePeople to organise the meetups together

---

# ✨ But before you do, there are a few things to know✨

Please take a look at this information before submitting your issue.

## Before starting a new community group

1. **[Check if there is already an official community](https://jamstack.org/community) in or near your city** - If so, it would be worth joining and supporting that group before deciding to add another. And the organizers of Jamstack groups are likely to welcome some support.
1. **Organizing an official group takes some commitment** - We're so excited that you've come this far, and we want you to succeed. We ask orgaizers to aim to hold meetings (physical or virtual) at least 3 times a year.

## What you need

1. **An online event space** - Most groups use Meetup.com or Facebook to coordinate their events, but you can use a different tool of your preference. What we encourage is that organizers publish events publicly on a neutral platform.
1. **A published and actionable code of conduct** - To help the community stay inclusive, safe, and welcoming. 

### Resource kit

We'll provide a resource kit with logos and branded assets for you to use. We'd like you to make use of the official Jamstack logo where approporiate, but don't let us stiffle your creativity. Some meetups have also added their own fun aesthetic and that's great too.

### Links and listings

We'll add a link to your events page to the [community section](https://jamstack.org/community) of the official Jamstack site. And if you provide a feed of your upcoming and previous events, we'll also add your events to the listings.

### Community and support

Each Jamstack community group gets their own channel in the [Jamslack](https://jamstack.org/jamslack) to help coordindate your event and communicate with your local community.

You can also speak to other group organizers and reach us for support via in the Jamslack as members of the private organizers admin channel.

### Code of Conduct

We have [a boilerplate code of conduct]() which you can use as a starting point. Please note that you will need to customise this for you and your group. It is vital that the information about how people can contact you and how action may be taken is correct for your group rather than being generic.

### Content and speakers

Recruiting speakers and putting together compelling content can be one of the biggest challenges for User Group leaders. We encourage you to reach out to your fellow user group leaders via [Slack](https://jamstack.org/slack) for ideas, and even consider partnering with them for virtual events or workshops.

## Jamstack Conf

[Jamstack Conf](https://jamstackconf.com) is an annual event for the global Jamstack community and provides a great opportunity for local community groups to participate, apply for awards, and share their knowledge. Active Jamstack user group leaders receive special incentives and activities during this event, and we're keen to get them more involved in helping shape the event. You can [watch videos](https://www.youtube.com/playlist?list=PL58Wk5g77lF94tg-F3y5zRyDeLVhTDnTg) from recent events to help spur content ideas and identify potential speakers for your meetup

**Comment by bigash42** [comment]
@Dawntraoz @jhvanderschee Very excited to have you two collaborating on bringing a Jamstack group to Amsterdam! 

Next steps: 

- Create a public group where people can find information about your events. We'll need this to link from your group on jamstack.org/community. We suggest meetup or facebook, but it's up to you were you host, just as long as it's open and discoverable. 
- Remember to have a code of conduct on your group page. 

I will work on an introduction with PassionatePeople 👍

**Comment by Dawntraoz** [comment]
@jhvanderschee has created the meetup page, now we are organizers and we will add the code of conduct.
Here is the link https://www.meetup.com/jamstack-amsterdam/

**Comment by Dawntraoz** [comment]
We just add the code of conduct as meetup page: https://www.meetup.com/jamstack-amsterdam/pages/31145779/Code_of_conduct/?name=Code_of_conduct&id=31145779
Let us know if we need to update something @bigash42 💕

We are almost there!!

**Comment by philhawksworth** [comment]
Woohoo! Excited to see a meetup happening in Amsterdam. Your meetup has been added to the community page and any events that you list on meetup should get pulled into the site. Let us know if you see any issues, @Dawntraoz!

https://jamstack.org/community/

**Comment by jhvanderschee** [comment]
I has been a while... and Corona... but we have held our first meetup! The Jamstack Amsterdam group now has 85 members and 10 showed up at our first event. We got 4 reviews (5 stars) and some great reactions in the discussion panel. We are looking forward to the next event.
