### ISSUE TITLE
Broken CSS for filters in generators dropdown

### ISSUE THREAD

**Issue by hegerdes** [jamstack/jamstack.org#490]
Hi,

I noticed that the CSS is broken or more preise not correctly assigned on the dropdown filters on the Generators site. It only shows white text on white background. Only if you hover you can see the dropdown entry's:

![CSS Error](https://i.imgur.com/5rZkV7o.png])

I fixed it in Dev-Tools by changing:

`<select data-filter-bind="language" data-filter-delimiter="," class="text-white py-1 px-2 rounded-default border border-white bg-transparent">`

To:
`<select data-filter-bind="language" data-filter-delimiter="," class="text-black py-1 px-2 rounded-default border border-white bg-transparent">`

So **text-black** instead of **text-white**

**Comment by PRiMENON** [comment]
confirmed.

fine:
* Mozilla Firefox

bad:
* Google Chrome
* Microsoft Edge(based chromium)

**Comment by vijethx** [comment]
`<select data-filter-bind="language" data-filter-delimiter="," class="text-white py-1 px-2 rounded-default border border-white bg-transparent">`
This is what you get when you change `text-white` to `text-black` : 
![image](https://user-images.githubusercontent.com/38877972/103353734-972e1f00-4acf-11eb-92cc-2d1012ffa804.png)

**Comment by hegerdes** [comment]
@vijethx 
Yes, but I overlooked the problem with the selected item. Black on black. Maybe its best to change the bg-transpaent tag.

**Comment by zachleat** [comment]
Ready for review here: https://github.com/jamstack/jamstack.org/pull/496

**Comment by zachleat** [comment]
Thanks for the report y’all!
