### ISSUE TITLE
Clipped security icon on homepage

### ISSUE THREAD

**Issue by toddmorey** [jamstack/jamstack.org#493]
Small bug: The icon for security on the homepage appears to be clipped a little funny:
<img width="94" alt="image" src="https://user-images.githubusercontent.com/885033/103565649-49763580-4e86-11eb-8c63-b278ce1fadb3.png">

Seeing this appearance in both Chrome and Safari.

**Comment by zachleat** [comment]
Ready for review here: https://github.com/jamstack/jamstack.org/pull/495
