### ISSUE TITLE
Nuxt.js Launch on Netlify button no longer works.

### ISSUE THREAD

**Issue by anjackson** [jamstack/jamstack.org#538]
If you go to https://jamstack.org/generators/ or https://jamstack.org/generators/nuxt/ and click on `Deploy to Netlify`, it doesn't work 😢 . The referenced repo, https://github.com/martinx3/nuxt-starter, has gone!  Perhaps it looked like this one: https://github.com/lukeocodes/nuxt-starter-netlify-cms but I never saw it so I don't know.

Thanks for JAMStack.org - it's great!

**Comment by zachleat** [comment]
Verified that this is broken but I’m not sure what a good alternative is? They seem to recommend use of create-nuxt-app now

**Comment by philhawksworth** [comment]
I think the suggested repo is a good call (https://github.com/lukeocodes/nuxt-starter-netlify-cms)
This deploys successfully.
