### ISSUE TITLE
Small typo on atomic deploys glossary page

### ISSUE THREAD

**Issue by lsell** [jamstack/jamstack.org#541]
be is repeated

<img width="522" alt="Screen Shot 2021-03-23 at 10 16 27 AM" src="https://user-images.githubusercontent.com/2154772/112170264-ebbdd380-8bc0-11eb-8955-eb8e33ae79f8.png">

**Comment by philhawksworth** [comment]
Good eye, @lsell!
Fixed. Thanks.
