### ISSUE TITLE
It is not fair for keystone

### ISSUE THREAD

**Issue by ali-r** [jamstack/jamstack.org#546]
![image](https://user-images.githubusercontent.com/6212683/113340137-bf345500-9340-11eb-9317-879c9d08b725.png)

please use beter repository for keystone in headless-cms part.

**Comment by JedWatson** [comment]
oof, just saw this too. a lot of people used to find Keystone through `headlesscms.org` and I was wondering why that dropped off... looks like this has somehow been redirected to our maintenance fork for `keystone-5` while we work on the major upcoming release, **Keystone 6** in the main repo.

It's a bit rough that Keystone looks like a tiny, brand new project with 40 stars, when we've been around for years and accumulated a lot more than that! will be submitting a PR asap to fix this

**Comment by raveling** [comment]
#601 attempts to remedy this.

Thanks @ali-r for raising this!

cc @philhawksworth @huguestennier 🙏

**Comment by zachleat** [comment]
Merged, thanks y’all!
