### ISSUE TITLE
Incorrect star count for static site generators

### ISSUE THREAD

**Issue by BlazerYoo** [jamstack/jamstack.org#562]
The star counts for the static site generators on https://jamstack.org/generators/ are incorrect. Ex. Hugo had 51,655 stars as of 9:43 am on 5/5/2021. But the websites shows 51,360.

**Comment by zachleat** [comment]
The builds here historically have not been automated to run on a schedule so you’re absolutely right that they can get outdated if we’re not committing to the `main` branch regularly.

So, let’s fix that! I opened a PR to run the build daily to update all of the stars https://github.com/jamstack/jamstack.org/pull/607

**Comment by zachleat** [comment]
Merged. We should see daily builds on the site now.
