### ISSUE TITLE
Possible outdated URL for TinaCMS

### ISSUE THREAD

**Issue by returnDanilo** [jamstack/jamstack.org#571]
The [TinaCMS page under Headless CMS](https://jamstack.org/headless-cms/tinacms/) currently points to https://tinacms.org/ but the site doesn't work. I googled for tinacms and the site  https://tina.io/ popped up and it seemed to be correct; to verify, I went to the repo https://github.com/tinacms/tinacms and it does point to the later as well.

**Comment by zachleat** [comment]
Hmm, it looks like a redirect is in place now for this. I’d merge a PR for this to update to the new domain but for now it seems okay.
