### ISSUE TITLE
URGENT: update Slack Join link on community page

### ISSUE THREAD

**Issue by bigash42** [jamstack/jamstack.org#581]
We need to quickly update the URL that currently exists for the slack icon on jamstack.org homepage. This link is somehow tied to an individual community member and they are getting flooded with notifications we can't turn off. 

![image](https://user-images.githubusercontent.com/14846680/120547616-3a000780-c3a6-11eb-957b-2c556d18443f.png)

The new link: https://jamstack.slack.com/

**Comment by bigash42** [comment]
Updating to invite link: https://join.slack.com/t/jamstack/shared_invite/zt-qkent5tv-0D0Nu3M1rJEHhVHE4zUMBw

Does not expire

**Comment by zachleat** [comment]
Closing this per the discussion on the PR https://github.com/jamstack/jamstack.org/pull/582#issuecomment-853378162

**Comment by yinonov** [comment]
> Updating to invite link: https://join.slack.com/t/jamstack/shared_invite/zt-qkent5tv-0D0Nu3M1rJEHhVHE4zUMBw
> 
> Does not expire

![image](https://user-images.githubusercontent.com/15140652/141672345-b7f71e08-db53-4684-80d8-a983f5f5a907.png)
