### ISSUE TITLE
Starting a meetup group in Barcelona

### ISSUE THREAD

**Issue by danurbanowicz** [jamstack/jamstack.org#638]
You're interested in starting a Jamstack community in your area?
AMAZING! We're keen to help. 🥳

Read this first 👉  [The Handbook](https://netlify.notion.site/Jamstack-Meetup-Handbook-42a5bf83e4eb4034bb485d81f5129cfb)

## Now that you've read the handbook, pease tell us:

1. **The city or region for you new Jamstack Community**: `Barcelona, Spain`
1. **When you plan to hold your first event**: `Next event planned for September 8th 2021, first event was June 1st 2021`
1. **How regulalry you plan to meet**: `One a month`
1. **How else we might be able to help**: `Connect us with potential speakers, sponsorship or discounts for members etc`
1. **Give us the link to your meetup page: `https://meetup.com/jamstack-barcelona`

---

After your issue has been submitted we will review it and contact you as quickly as we can. Thanks for your patience as we work through the requests.

**Comment by danurbanowicz** [comment]
As well as our [meetup.com page](https://www.meetup.com/jamstack-barcelona/), the Jamstack Barcelona group also has a website (built with Eleventy and deployed to Netlify) including a Code of Conduct page, here: https://jamstackbarcelona.dev/

**Comment by philhawksworth** [comment]
The looks fantastic Dan!
It seems like you are already up and running and looking good!
I’ll add you to the community page with much delight.


Phil Hawksworth
Director of Developer Experience, Netlify
@philhawksworth
