### ISSUE TITLE
automatically get thumbnails of the example websites

### ISSUE THREAD

**Issue by hbakhtiyor** [jamstack/jamstack.org#68]
what do you think about this?

now contributors can add their show cases with ease without manually capturing & cropping their screen-shots.

you can automatically get thumbnails of the example websites, always up-to-date (by our specific period) screenshots, without stale 

e.g.

```
https://api.letsvalidate.com/v1/thumbs?url=http://www.sphero.com/&width=596&height=396
```

<details>

  <summary>Result:</summary>
  
  <img src="https://api.letsvalidate.com/v1/thumbs?url=http://www.sphero.com/&width=596&height=396" width="596" height="396" alt="Thumbnail Preview">
</details>

```html
<img src="https://api.letsvalidate.com/v1/thumbs?url={{ .link }}&width=596&height=396"/>
```

you can learn more about the api at the [github repo](https://github.com/letsvalidate/api)

**Comment by jhabdas** [comment]
This API is pretty slick. Could be run with a cron task to help keep the examples up-to-date as well, and help normalize the things they're using while affording the ability to hyperlink directly to the underlying technologies.

**Comment by hbakhtiyor** [comment]
@jhabdas thanks, don't need to complicate with cron task, it'll auto update by our hard-coded max-age (not yet expose to public)

**Comment by verythorough** [comment]
Very cool, @hbakhtiyor! Are there any fees associated with using your API?

**Comment by hbakhtiyor** [comment]
it's free, since your website consume very small amount, just mention at readme or somewhere and share it ;)

**Comment by PerrySetGo** [comment]
closing this - interesting, but issue seems stale at this point.
