### ISSUE TITLE
Starting a meetup group in São Paulo, Brazil

### ISSUE THREAD

**Issue by edlller** [jamstack/jamstack.org#680]
You're interested in starting a Jamstack community in your area?
AMAZING! We're keen to help. 🥳

Read this first 👉  [The Handbook](https://netlify.notion.site/Jamstack-Meetup-Handbook-42a5bf83e4eb4034bb485d81f5129cfb)

## Now that you've read the handbook, pease tell us:

1. **The city or region for you new Jamstack Community**: `Sao Paulo, Brazil`
1. **When you plan to hold your first event**: `January 6th 2022`
1. **How regulalry you plan to meet**: `We expect to have meeting every quarter`
1. **How else we might be able to help**: `I want to create courses and documentation in Brazilian portuguese.`
1. **Give us the link to your meetup page: `https://www.meetup.com/pt-BR/jamstack-saopaulo`

---

After your issue has been submitted we will review it and contact you as quickly as we can. Thanks for your patience as we work through the requests.

**Comment by domitriusclark** [comment]
Hey @edlller is this something you're still interested in? 

Taking over support for communities and meetups and reaching back out to see what I can do to support.

If not, I can close out this issue this week 👍

**Comment by edlller** [comment]
Hello,
Sorry for the delay, I have being too busy these days.
I would like to have a quick talk to you to explain the problems we are
facing and try exchange some ideas.
When are you available?
Best regards,

Edller

Em seg., 1 de ago. de 2022 às 02:02, Domitrius ***@***.***>
escreveu:
