### ISSUE TITLE
The link pointing to the Slack channel is not active anymore

### ISSUE THREAD

**Issue by iaeiou** [jamstack/jamstack.org#689]
Hi,

in the footer of jamstack.org, there is a link "Chat on Slack".

Following this link redirects to the Slack website, but the page reads "This link is no longer active"

**Comment by rizkiheryandi** [comment]
![image](https://user-images.githubusercontent.com/25028868/145673996-17294515-c7d4-4ada-a149-90e0d20a16df.png)

Yes, hope the link update soon

**Comment by iaeiou** [comment]
Fixed! (Slack has been replaced by a Discord channel)
