### ISSUE TITLE
Starting a meetup group in [this beautiful city]

### ISSUE THREAD

**Issue by juliuszfedyk** [jamstack/jamstack.org#722]
You're interested in starting a Jamstack community in your area?
AMAZING! We're keen to help. 🥳

Read this first 👉  [The Handbook](https://netlify.notion.site/Jamstack-Meetup-Handbook-42a5bf83e4eb4034bb485d81f5129cfb)

## Now that you've read the handbook, pease tell us:

1. **The city or region for you new Jamstack Community**: `Jamsville, Australia`
Warsaw, Poland
2. **When you plan to hold your first event**: `January 1st`
We already held the forst meetup on January 27th 2033:
https://www.meetup.com/jamstack-meetup-warsaw/events/282732758/
https://www.youtube.com/watch?v=h_E8CcajbfE
3. **How regulalry you plan to meet**: `Every other month`
Every Month
4. **How else we might be able to help**: `Connect us with potential speakers`
Connect us with potential speakers
5. **Give us the link to your meetup page: `https://meetup.com/jamstack-{your meetup city}`
https://www.meetup.com/jamstack-meetup-warsaw

Notes:
 - we run the meetups predominantly in Polish as most people that would benefit from them are a bit intimidated by English. We are very open to including English speakers and running them bilingual.
 - We do not require Meetup fee coverage, as we are sponsored by Performance Media, we would love to ask you for help with connecting with speakers and the wider community.

---

After your issue has been submitted we will review it and contact you as quickly as we can. Thanks for your patience as we work through the requests.

**Comment by juliuszfedyk** [comment]
HI @philhawksworth - still waiting for a contact from you guys :)

**Comment by domitriusclark** [comment]
Hey @juliuszfedyk!

Sorry for the late response! Just reviving support for meetups & communities. This still something you're interested in?
