### ISSUE TITLE
Starting a meetup group in Aba

### ISSUE THREAD

**Issue by davidconoh** [jamstack/jamstack.org#791]
You're interested in starting a Jamstack community in your area?
AMAZING! We're keen to help. 🥳

Read this first 👉  [The Handbook](https://netlify.notion.site/Jamstack-Meetup-Handbook-42a5bf83e4eb4034bb485d81f5129cfb)

## Now that you've read the handbook, pease tell us:

1. **The city or region for you new Jamstack Community**: `Aba, Nigeria`
1. **When you plan to hold your first event**: `October 8th`
1. **How regularly you plan to meet**: `Once a quarter`
1. **How else we might be able to help**: `Connect us with potential speakers and sponsorships`
1. **Give us the link to your meetup page: `https://meetup.com/jamstack-aba`

---

After your issue has been submitted we will review it and contact you as quickly as we can. Thanks for your patience as we work through the requests.

**Comment by domitriusclark** [comment]
Hey @davidconoh 

Could you actually fill out [this form](https://forms.gle/TzuFVHJ27rX3oaQU6) for me? I've moving the capture of info to there. Thank you so much

**Comment by davidconoh** [comment]
Done!
