### ISSUE TITLE
How long does it take PR's to be reviewed and merged

### ISSUE THREAD

**Issue by kentmz** [jamstack/jamstack.org#843]
I created a [PR](https://github.com/jamstack/jamstack.org/pull/829) back in October and it is still open and I can see PR's open since 2021. Is there a timeline as to when these will be reviewed and approved?

**Comment by aerphanas** [comment]
maybe maintainers are on vacation as you can see in this [discussion](https://github.com/jamstack/jamstack.org/discussions/702#discussion-3742152)

**Comment by alianza** [comment]
Still seems to take quite long, and a long list of PR currently open...

**Comment by TomasBankauskas** [comment]
@kentmz I'm closing this issue as your PR has been merged.
