### ISSUE TITLE
Missing GitHub statistics for static site generator and CMS listing items

### ISSUE THREAD

**Issue by thibaudcolas** [jamstack/jamstack.org#862]
Spotted as part of #860. A large number of items don’t have statistics displayed from GitHub, even though they set their `repository`. For example,

- CMS [Netlify CMS](https://jamstack.org/headless-cms/netlify-cms/)
- CMS [Pimcore](https://github.com//pimcore/pimcore)
- SSG [Slick](https://jamstack.org/generators/slick/)
- SSG [Docsy](https://jamstack.org/generators/docsy/)

This could be a bug in the [data fetching](https://github.com/jamstack/jamstack.org/blob/main/src/site/_data/github.js#L26), or perhaps an issue with some of the metadata of those projects (see for example #861).

**Comment by martinjagodic** [comment]
Like @hexagoncircle mentioned, this is probably an access token or rate-limiting problem. When I run this locally it works. Could someone with access re-generate the GitHub access token and re-deploy the site to test this hypothesis?

cc @zachleat

**Comment by hexagoncircle** [comment]
It's indeed an expired token. This should be fetching stats properly again. Let me know if you see any other issues. Thanks all!
