### ISSUE TITLE
Volunteering as an admin

### ISSUE THREAD

**Issue by breck7** [jamstack/jamstack.org#970]
Seems like there is a big backlog of issues (59 PRs and 67 Open issues).

I'd like to volunteer to be added as an admin.

I've been on Github since 2009 (~15 years!) and have created/maintain a number of decently popular repos such as PLDB.io (https://github.com/breck7/pldb)

**Comment by breck7** [comment]
@philhawksworth @zachleat

**Comment by TomasBankauskas** [comment]
Thank you for volunteering @breck7, currently I will take care of the repo.
