### ISSUE TITLE
New JAMstack community: Toulouse

### ISSUE THREAD

**Issue by DirtyF** [jamstack/jamstack.org#99]
Please add [JAMstack Toulouse](https://www.meetup.com/JAMstack-Toulouse/) to [https://jamstack.org/community/](https://jamstack.org/community/)

[First meetup scheduled in March](https://www.meetup.com/fr-FR/JAMstack-Toulouse/events/246940796/) with @philhawksworth from @Netlify and @pixelastic from @Algolia. (to be confirmed).

Cheers! 🥂

**Comment by DirtyF** [comment]
Also I noticed the join CTA stil points to cassandra@netlify.com, maybe change it to an alias like meetups@netlify.com?

**Comment by philhawksworth** [comment]
Thanks @DirtyF I'll get those changes organised.

Could you suggest a suitable landmark for the Toulouse chapter of the JAMstack community?
Something suitable to go here:
https://jamstack.org/community/

**Comment by DirtyF** [comment]
Thanks @philhawksworth, here is picture of "Le Capitole", one of the most idiomatic building of the city.

<img alt="Le Capitole, Toulouse" src="https://media-cdn.tripadvisor.com/media/photo-s/09/74/7f/63/place-du-capitole.jpg"/
